apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-4"
  name: argocd-apps
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: platform
  sources:
    - chart: argocd-apps
      helm:
        valueFiles:
        - $values/argocd/base/values/argocd-apps.yaml
      repoURL: https://argoproj.github.io/argo-helm
      targetRevision: 2.0.0
    - ref: values
      repoURL: https://github.com/irizzante/cluster-addons.git
      targetRevision: HEAD
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - PruneLast=true
    - CreateNamespace=true