apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
  annotations:
    argocd.argoproj.io/sync-wave: "-4"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: external-secrets
    server: 'https://kubernetes.default.svc'
  sources:
  - repoURL: 'https://charts.external-secrets.io'
    targetRevision: 0.9.9
    chart: external-secrets
    helm:
      valueFiles:
      - $values/argocd/base/values/external-secrets.yaml
  - repoURL: 'https://github.com/irizzante/cluster-addons.git'
    targetRevision: HEAD
    ref: values
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - PruneLast=true
      - CreateNamespace=true
