apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets-manifests
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: 'https://kubernetes.default.svc'
  source:
    path: argocd/components/externalsecrets-bitwarden/cluster-secret-store
    repoURL: https://github.com/irizzante/cluster-addons.git
    targetRevision: HEAD
  project: platform
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
    syncOptions:
      - CreateNamespace=true