projects:
  platform: 
    namespace: argocd
    description: Platform team project
    sourceRepos:
      - "*"
    destinations:
      - namespace: "*"
        server: "*"
    clusterResourceWhitelist:
      - group: "*"
        kind: "*"
    namespaceResourceWhitelist:
      - group: "*"
        kind: "*"

  apps:
    namespace: argocd
    description: App team project
    sourceRepos:
      - "*"
    destinations:
      - namespace: "!argocd"
        server: "*"
      - namespace: "!kube-system"
        server: "*"
    clusterResourceBlacklist:
      - group: "*"
        kind: "*"
    namespaceResourceWhitelist:
      - group: "*"
        kind: "*" 